### ISSUE TITLE
can't resize or hide sidebar/action logger on mobile

### ISSUE THREAD

**Issue by jedwards1211** [storybooks/react-storybook#660]
Right now I can't make too much use of React Storybook on a small mobile phone because the sidebar and action logger get in the way.  I can't seem to drag them either, and the ability to hide them (since they're already at minimum size) would be nice.

That is, unless there's some way to do it that I don't know about...I can't see any obvious way at least.

![img_0022](https://cloud.githubusercontent.com/assets/1448194/21555112/c4b8d99a-cdda-11e6-9339-c3f6defa75eb.PNG)

**Comment by camjc** [comment]
If you click on that command-key looking button next to `REACT STORYBOOK` it'll tell you all the keyboard shortcuts. I'm not sure if that helps you on mobile though since it may be impossible to do them.

Otherwise you can probably use @kadira/storybook-addon-options package to disable the sidebars.

**Comment by arunoda** [comment]
Actually we need a fresh UI for the mobile.
We are tracking it here: https://github.com/storybooks/storybook-ui/issues/57
